# Generated by Django 3.1.6 on 2021-04-12 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cooking', '0002_auto_20210411_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Snack', 'Snack')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='region',
            field=models.CharField(choices=[('America', 'America'), ('Europe', 'Europe'), ('Africa', 'Africa'), ('Asia', 'Asia'), ('Australia', 'Australia')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='timeToCook',
            field=models.CharField(choices=[('1-30 minutes', '1-30 minutes'), ('31-60 minutes', '31-60 minutes'), ('61+ minutes', '61+ minutes')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
